env:
  commonjs: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  "import/no-unresolved": [ 
    2, 
    { 
      caseSensitive: false 
    } 
  ]
}
